version: '3.8'

services:
  telegram-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: send-telegram-message
    ports:
      - "7777:8080"
    volumes:
      - ./api:/fastapi/api
      - ./api/HraniInfoSession.session:/fastapi/HraniInfoSession.session
    restart: unless-stopped

